# Generated by Django 4.0.4 on 2022-05-30 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0010_threadmodel_messagemode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageMode',
            new_name='MessageModel',
        ),
    ]
