# Generated by Django 4.0.4 on 2022-05-31 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_tag_comment_tags_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
